[tools]
k3d = "latest"
k9s = "latest"
kubectl = "latest"
pre-commit = "latest"
python = "3.13"
ruff = "latest"
uv = "latest"

[settings]
python.uv_venv_auto = true
idiomatic_version_file_enable_tools = ["python"]
experimental = true

[env]
APP_REPO = 'devops-master-project'
GITOPS_REPO = 'devops-master-project-gitops'

[hooks]
enter = "bash ./scripts/setup_project"

[tasks.k8s-setup-local]
description = "Set up a  Kubernetes cluster that builds the local images and applies them"
run = "bash ./kubernetes/setup_cluster_local"


[tasks.e2e-test]
description = "Running end-to-end tests on the kubernetes deployment."
run = "cd ./kubernetes && uv run e2e_test.py"
